server:
  port: 8088

spring:
  application:
    name: easy-deploy-web
  datasource:
    url: jdbc:postgresql://localhost:5432/easydeploydb
    driverClassName: org.postgresql.Driver
    username: easydeploy
    password: easydeploy_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.easydeploy: DEBUG
